---
- name: Add KPI System User
  user:
    name: "{{ kpi_nvm_user }}"
    shell: /bin/bash
    group: "{{ kpi_system_group }}"
    force: yes
    append: yes
    createhome: yes
    home: "{{ kpi_system_user_home }}"

- name: Install NVM and Global Node Packages
  include_tasks: install-nvm.yml
  tags:
   - nvm

# adding the following task because sometimes error in 
# https://github.com/sass/node-sass/issues/1579 is triggered
# - name: Re-install node-sass # noqa 301
#   command: "{{  kpi_nvm_npm_path }} rebuild node-sass"
#   environment:
#     PATH: "{{ kpi_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"

- name: Copy client-side config file
  template:
    src: templates/kpi/config.es6.j2
    dest: "{{ kpi_static_path }}/js/config.es6"
    mode: 0644

- name: Build client code # noqa 301
  command: "{{ kpi_nvm_npm_path }} run copy-fonts && {{  kpi_nvm_npm_path }} run build"
  args:
    chdir: "{{ kpi_checkout_path }}"
  environment:
    PATH: "{{ kpi_nvm_node_dir }}/bin:{{ ansible_env.PATH }}"
    HOME: "{{ kpi_system_user_home }}"
  notify:
    - restart_service

- name: Patch libgeos.py file for updated regex
  patch:
    src: templates/django_virtualenv_dir/site-packages/django/contrib/gis/geos/libgeos.py
    dest: "{{ kpi_venv_path }}/local/lib/python2.7/site-packages/django/contrib/gis/geos/libgeos.py"
    basedir: "{{ kpi_checkout_path }}"


- name: syncdb, migrate and collect static files
  django_manage:
    command: "{{ item }}"
    app_path: "{{ kpi_checkout_path }}"
    virtualenv: "{{  kpi_venv_path }}"
    settings: "{{ kpi_settings_app_name }}"
  with_items: "{{ kpi_django_setup_commands }}"
  notify:
    - restart_service
