---
- name: Converge
  hosts: all
  roles:
    - role: ansible-kpi
      kpi_pgsql_db: kpi
      kpi_pgsql_user: kpi
      kpi_pgsql_password: kpi
      kpi_enable_monitoring: false
      kpi_git_url: "https://github.com/onaio/kpi.git"
