---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu-16.04
    image: solita/ubuntu-systemd:16.04
    privileged: true
    command: /sbin/init
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
provisioner:
  name: ansible

verifier:
  name: testinfra
