---
- name: Converge
  hosts: all
  roles:
    - role: onaio.postgresql
      postgresql_backup_enabled: false
      postgresql_version: 9.6
      postgresql_users:
          - name: kpi
            pass: kpi
            encrypted: true
      postgresql_databases:
        - name: kpi
          owner: kpi
          encoding: "UTF-8"
    - role: ansible-kpi
      kpi_pgsql_db: kpi
      kpi_pgsql_user: kpi
      kpi_pgsql_password: kpi
      kpi_enable_monitoring: false
