---
name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Run Molecule tests
        uses: onaio/molecule-action@master
